{"name": "test_invalid_user_login", "status": "passed", "description": "\nAutomated Test Case: Verify that login fails for invalid user credentials.\n", "attachments": [{"name": "stdout", "source": "679cf491-697e-465b-908b-ab2120d8fcd4-attachment.txt", "type": "text/plain"}], "start": 1761760638078, "stop": 1761760639514, "uuid": "6a1b8019-9e15-49e7-87e3-5728a69fad4d", "historyId": "9668de7afec4aea2e85f39c25138877c", "testCaseId": "9668de7afec4aea2e85f39c25138877c", "fullName": "tests.test_login#test_invalid_user_login", "labels": [{"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-GG4538Q"}, {"name": "thread", "value": "27256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}